# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/realme_trinket/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),realme_trinket)

endif
